/*
 * Patient Treatment API
 *
 * Patient Treatment Tracking System API
 *
 * API version: 1.0.0
 * Contact: xkarunnyi@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type PatientsAPI interface {


    // ArchivePatient Delete /api/patients/:patientId
    // Archive a patient 
     ArchivePatient(c *gin.Context)

    // CreatePatient Post /api/patients
    // Creates a new patient 
     CreatePatient(c *gin.Context)

    // GetPatient Get /api/patients/:patientId
    // Get patient details 
     GetPatient(c *gin.Context)

    // GetPatients Get /api/patients
    // Provides the list of patients 
     GetPatients(c *gin.Context)

    // UpdatePatient Put /api/patients/:patientId
    // Update patient details 
     UpdatePatient(c *gin.Context)

}