/*
 * Patient Treatment API
 *
 * Patient Treatment Tracking System API
 *
 * API version: 1.0.0
 * Contact: xkarunnyi@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type PatientInput struct {

	// Name of the patient
	Name string `json:"name"`

	// Medical condition of the patient
	Condition string `json:"condition"`

	// Date when the diagnosis was made
	DiagnosisDate string `json:"diagnosisDate,omitempty"`

	// Date when the treatment started
	TreatmentStartDate string `json:"treatmentStartDate,omitempty"`

	// Expected date of treatment completion
	ExpectedCompletionDate string `json:"expectedCompletionDate,omitempty"`

	// Current status of the patient
	Status string `json:"status,omitempty"`
}
